name: plinko
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  webview_flutter: ^4.6.0
  flutter_local_notifications: ^13.0.0 
  flutter_localizations:
    sdk: flutter
  timezone: ^0.9.0 
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  uuid: ^4.5.1
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/json/
      - assets/fonts/
      - assets/images/


  fonts:
    - family: Mon
      fonts:
        - asset: assets/fonts/Montserrat-400.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-500.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-600.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-700.ttf
          weight: 700